### PR TITLE
More refactoring, minor UI changes

### PR DESCRIPTION
**Pull request by arkon**
- Moving constants (i.e. non-UI related) strings from XML to code files
- Shows a pink status bar instead of forcing full screen (which was sort of annoying)
- Revamp the APIUtil helpers
- Move auth token logic to AuthUtil

### CODE REVIEW

**Comment by J-Cotter** [comment]
First off let me say thanks for the initial cleanup. It was desperately needed to say the least. I am very grateful to have someone of your calibre contributing to the project.

Immediately upon looking at some of the changes you have made here, there are a few things of note that stood out to me.

https://github.com/J-Cotter/LISTEN.moe-Unofficial-Android-App/pull/2/commits/ecf52e1ed661e9eeba7656a83e026605bab75eb4 [breaks the scaling entirely](https://snag.gy/Cbi7pr.jpg). XML was what I tried first when attempting the image scaling, but it does not seem to work in this particular instance.

https://github.com/J-Cotter/LISTEN.moe-Unofficial-Android-App/pull/2/commits/2180ec0c5f9c8dfa0927195e47f2a3f89e8ac2d1 I purposefully chose to make the app full screen. Personally I find it more aesthetically pleasing without the system UI.

https://github.com/J-Cotter/LISTEN.moe-Unofficial-Android-App/pull/2/commits/150282eed27cb4b1785e48419fbe8d036f8dc157 I see no practical use in using GSON given how little JSON is being parsed at any one time. The default JSON library works fine.

These were just a few of the things I immediately noticed. As well as that I feel that the amount of abstraction is unnecessary and only complicates things by creating a number of files all essentially doing the same thing e.g all the interface callbacks.

Also the requested by text seems to not be working. [Website](https://snag.gy/oaCXtK.jpg) | [App](https://snag.gy/GPjSRd.jpg). I have not looked into why, but I thought you should be notified of it.

I feel like I should clarify that none of the code is bad in any way. In fact it is much better than any code I have written, both in form and function. I believe it is my fault for not properly laying out the design goals I had in mind for the project. Going forward I believe communication both ways is needed in order to effectively contribute to a shared objective rather than individual commits resulting in a mishmash of different features and designs.

**Comment by arkon** [comment]
@J-Cotter Hey! I couldn't tell how much response I'd get since your GitHub profile is relatively empty, so I'm glad there was a response to this PR.

I've fixed the requested by part, but I'll need to look into the background scaling a bit more. I was hoping to refactor the layout for that activity as well.

I think that ultimately, the abstraction is something that is typical of Java/Android projects, as it's considered best practice to have it "truly" object-oriented. GSON is just a useful tool for directly mapping the JSON responses from the API to the Java objects. It definitely helps maintaining the project a lot easier, since it's easier to find things and not necessarily be concerned with how the response data is parsed and used mixed with the activity/service logic.

I'd actually argue that the status bar thing is an issue of form over function -- there's no real reason for the app to be full screen (it's not a game, nor is it presenting some form of media like photos or videos), and hiding the status bar information from users might actually be bothersome (as I usually find it to be, since I can't easily see notifications or the time at a glance anymore). If you feel very strongly against it though, I can certainly revert it.

**Comment by J-Cotter** [comment]
The requested by still seems to not be working properly, it does not hide when no user requested the song ([Image](https://snag.gy/mHrbc7.jpg))
When a user did request the song it does not format it to make the user clickable. ([Image](https://snag.gy/o2P9j8.jpg)) Should link to [Here](https://forum.listen.moe/u/robflop) in this case.

The background still seems to be broken despite the revert, which is interesting....

I would try to fix some of these issues but I am still trying to figure out how everything comes together, now that most things have been refactored. I am beginning to understand it though.

As for the abstractions, I still feel they make things more complicated than necessary but I am willing to go with it and see how things turn out. 

I can see why you prefer to not have full screen although given the app's nature I don't expect many users to actively have the main UI open for long. I am willing to compromise a little bit on this matter though. I think the best course of action would be to make it toggle-able. That way the end user could decide which they prefer. We would have to decide where to keep the toggle option though which would probably be the hardest part, trying to see where it would fit in best 😛

**Comment by arkon** [comment]
Alrighty, I fixed up the requested by visibility and link issues, and also made it so the background image takes up the full screen (but it fits so it crops now, instead of stretching weirdly -- let me know how you feel about that).

I also added some padding to the "Powered by: ..." and "Current listeners: ..." TextViews at the bottom so they weren't right up at the edge of the screen.

As for the toggling, I can definitely get behind that idea. My idea for improving the UI is vaguely along this idea:
- Single activity, with tabs at the top
- Tabs are part of a transparent AppBar: main radio fragment and user favourites
- AppBar's menu (on the right) has a search icon and an overflow menu
- Search would toggle a search interface, similar to other apps
- Overflow could contain Login/Logout (logging in would be via a dialog), About (a dialog with information about the app and LISTEN.moe), and perhaps the toggle for fullscreen

**Comment by arkon** [comment]
Oh yeah, a side effect of this PR including the models/gson is also that we now have all the information required for adding: Song History, Display Requests Remaining, and Display Number of Songs in Queue.

**Comment by J-Cotter** [comment]
The background seems inexplicably weird now. That being said it works fine although it was nice being able to see the entire background before even if the width was being squashed to make it fit. 

The padding makes a massive difference making it feel more polished.

I like your plans for the UI, it all sounds pretty good although I feel like I need to see something to really get a feel for it.

I did notice the extra info you were parsing which means that can be implemented fairly soon.

I would say that this PR is almost ready to merge into master. I just need to make sure everything is working 100% before I do so. After that we can begin to work on implementing the new features and a new release. 
I might release the current master branch as is due to a number of fixes I feel should be released before we tackle adding the new features.

**Comment by arkon** [comment]
I agree, I think a lot of these (and future) changes would belong in a major revision.

**Pull request merged**
